### ISSUE TITLE
使用最新的a3脚本无法更新CK

### ISSUE THREAD

**Issue by collickliu** [ma-xin/JDCKWebApp#2]
# 开始执行... 2022-08-14 19:21:05

当前脚本版本号：a3.2

开始查询GitEE的CK

https://gitee.com/api/v5/repos/collick/jdck_tmp/issues/I5M7VS/comments?access_token=1193313fd45223dgkdlkoe22b62980&page=1&per_page=20&order=asc

请求状态 【200】

检测到共有【1】个cookie

获取到/ql/data/config/auth.json的缓存token
检验token地址:http://127.0.0.1:5700/api/envs?searchValue=&t=1660476066791

已获取到有效token

当期青龙版本：2.12.2

任务:拉取Gitee上的CK
时间:2022-08-14 19:21:06
共检测到1个CK
开始处理第1个cookie：【pt_key=AAJi-MmmADD1Pf0SKC37vIjT8_NwPOtodjsw839-0fdhjvcalplvgTA;pt_pin=lick12;】

查询到【1】

查询到1个CK【lick12】，开始修改 
id:18
CK写入青龙异常。'NoneType' object has no attribute 'split'

'NoneType' object has no attribute 'split'

Traceback (most recent call last):
  File "/ql/data/scripts/connectGitee.py", line 451, in <module>
    flag = handleEnv(ql_token, git_value)
  File "/ql/data/scripts/connectGitee.py", line 250, in handleEnv
    flag = saveEnv(token, _id, cookie, _remarks, False)
  File "/ql/data/scripts/connectGitee.py", line 269, in saveEnv
    rs = remarks.split('^^',1)
AttributeError: 'NoneType' object has no attribute 'split'

## 执行结束... 2022-08-14 19:21:06 耗时 1 秒

这种情况是因为 青龙版本过高导致的吗？

**Comment by ma-xin** [comment]
这是我定义了备注格式，要是在错误中看到最后两行的错误，要么删掉青龙面板上的这条cookie ， 要么手动改一下这条cookie的备注格式，在原备注前加上 “日期^^”，例如：【2022-12-26^^原备注】
